# Generated by Django 3.2 on 2021-07-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourvariation',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colourvariation',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='cart.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_category_fr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='cart.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fr',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sizevariation',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sizevariation',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
