# Generated by Django 3.2 on 2021-07-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
