# Generated by Django 3.2 on 2021-07-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_comment_approuved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approuved',
            new_name='approved',
        ),
    ]
