# Generated by Django 3.2 on 2021-07-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_rename_approuved_comment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
